apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-0fvv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-0fvv
    app.kubernetes.io/part-of: tkwch-fix-0075-0004-app
  name: devfile-sample-0fvv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-0fvv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-0fvv
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0004-tenant/tkwch-fix-0075-0004-app/devfile-sample-0fvv@sha256:2180d5f631292ccf1a8c9a196bb8d9f61e1c6359fd3ea8c3d119c2a27b65adfb
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
